name: Go Tests

on:
    push:
        branches: ["backend_main"]
    pull_request:
        branches: ["backend_main"]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21"

            - name: Install dependencies
              run: go mod tidy
              working-directory: . # 👈 repo root (where go.mod is)

            - name: Run Unit Tests
              run: go test ./... -v

            - name: Generate Coverage Report
              run: go test ./... -coverprofile=coverage.out
